/**
 * Tool definition compatible with OpenAI function calling specification.
 * Contains the function signature and metadata required for LLM tool invocation.
 */
export interface Tool {
  readonly type: "function";
  readonly function: {
    readonly name: string;
    readonly description: string;
    readonly parameters: {
      readonly type: "object";
      readonly properties: Record<
        string,
        {
          readonly type: string;
          readonly description?: string;
          readonly enum?: readonly string[];
        }
      >;
      readonly required: readonly string[];
    };
  };
}

/**
 * Represents a tool call request generated by the LLM.
 * Contains the function name and serialized arguments to execute.
 */
export interface ToolCall {
  readonly id: string;
  readonly type: "function";
  readonly function: {
    readonly name: string;
    readonly arguments: string; // JSON string
  };
}

/**
 * Represents the result of a tool execution to be sent back to the LLM.
 * Contains the tool call ID and stringified result content.
 */
export interface ToolResult {
  readonly tool_call_id: string;
  readonly role: "tool";
  readonly content: string;
}

export interface ShellExecutorOptions {
  readonly timeout?: number;
  readonly cwd?: string;
  readonly env?: Record<string, string>;
}

export interface ShellResult {
  readonly stdout: string;
  readonly stderr: string;
  readonly exitCode: number;
  readonly duration: number;
  readonly error?: string;
}
